### ISSUE TITLE
[7.0] account_fiscal_position_rule_stock

### ISSUE THREAD

**Issue by rdeheele** [OCA/account-fiscal-rule#19]
Steps:
- install account_fiscal_position_rule_stock
- Create an incoming shipment or a delivery order
- Select a partner, the next traceback occurs:

Server Traceback (most recent call last):
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/2946724-7-0-95feb0/openerp/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/2946724-7-0-95feb0/openerp/netsvc.py", line 300, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/2946724-7-0-95feb0/openerp/service/web_services.py", line 632, in dispatch
    res = fn(db, uid, _params)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/2946724-7-0-95feb0/openerp/osv/osv.py", line 193, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/2946724-7-0-95feb0/openerp/osv/osv.py", line 133, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/2946724-7-0-95feb0/openerp/osv/osv.py", line 202, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/2946724-7-0-95feb0/openerp/osv/osv.py", line 190, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
TypeError: onchange_partner_in() takes at most 6 arguments (7 given)

**Comment by renatonlima** [comment]
Can we close this PR issue?

**Comment by rvalyi** [comment]
@renatonlima I believe this is a database where the warning module was installed and it brings an incompatible on_change. The other day with @danimaribeiro we decided that the  the best way to fix the issue would be the creation of an extra "glue" module to make the account_fiscal_position_rule_stock and the warning modules compatibles. Meanwhile this issue would still exist so we could leave it open until somebody makes such a module or that the warning module get trashed out of the Odoo official modules (you bet?).
See this comment and the next ones for details: https://github.com/OCA/account-fiscal-rule/pull/30#issuecomment-157576750

cc @rdeheele

**Comment by legalsylvain** [comment]
closing, due to inactivity, and obsolete version. (7.0).
