### ISSUE TITLE
[14.0] Avatax and Avatax sale API logging CAUSES exception

### ISSUE THREAD

**Issue by spadae22** [OCA/account-fiscal-rule#286]
## Module
account__avatax_sale

## Describe the bug
Try to calculate sales tax or confirm - causes exception

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo14/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo14/odoo/odoo/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo14/odoo/odoo/http.py", line 361, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo14/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo14/odoo/odoo/http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo14/odoo/odoo/http.py", line 914, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo14/odoo/odoo/http.py", line 533, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo14/odoo/addons/web/controllers/main.py", line 1398, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo14/odoo/addons/web/controllers/main.py", line 1386, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo14/odoo/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo14/odoo/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo14/odoo/chris_coffee_v14/ccoffee_sale_wkf/models/sale_stock.py", line 75, in action_confirm
    return super(SaleOrder, self).action_confirm()
  File "/opt/odoo14/odoo/chris_coffee_v14/account_avatax_sale/models/sale_order.py", line 214, in action_confirm
    self.avalara_compute_taxes()
  File "/opt/odoo14/odoo/chris_coffee_v14/account_avatax_sale/models/sale_order.py", line 202, in avalara_compute_taxes
    order._avatax_compute_tax()
  File "/opt/odoo14/odoo/chris_coffee_v14/account_avatax_sale/models/sale_order.py", line 161, in _avatax_compute_tax
    tax_result = avatax_config.create_transaction(
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo14/odoo/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo14/odoo/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: create_transaction() got an unexpected keyword argument 'log_to_record'
## To Reproduce
**Affected versions**: 14.0

1. In sales order, click Compute taxes or Confirm
2.
3.

**Expected behavior**
Compute sales tax and confirm sales order

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by metaminux** [comment]
Hi @spadae22

log_to_record was introduced in :

- account_avatax_sale by 3c18ec959178488532792b5325a48cbbcd7f6090
- account_avatax by its parent commit 79e31c15c5dd333f95d1fce3a76783ad8333e378

both were merged on April 22 with #276 

Is it possible you updated only account_avatax_sale and not account_avatax ?

Can you still reproduce this bug ?

**Comment by spadae22** [comment]
Oh, sorry it is resolved.

**Comment by metaminux** [comment]
Thanks @spadae22 can you close the issue then ?
