### ISSUE TITLE
[14.0] AttributeError: 'avalara.salestax' object has no attribute 'override_line_taxes'

### ISSUE THREAD

**Issue by armandoschianodicola** [OCA/account-fiscal-rule#343]
## Module
account_avatax_oca

## Describe the bug
calling avatax_compute_taxes() method of account.move or calling action_post() method of account.move throws the exception described above

## To Reproduce
**Affected versions**: 14.0 - commit be96e4f

1. create an invoice
2. click on COMPUTE TAXES button or click on CONFIRM button on an invoice

**Comment by dreispt** [comment]
Can you share the traceback please?
Is that specific to a specific invoice? Can you share the corresponding details?

**Comment by armandoschianodicola** [comment]
Here you go. Maybe the origin of the error is the missing dependency of account_avatax_sale_oca module inside account_avatax_oca's depends since override_line_taxes is defined in account_avatax_sale_oca and called in account_avatax_oca

Error:
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/odoo/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 361, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 914, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 533, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1392, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1380, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/user/OCA/l10n-italy/l10n_it_fatturapa_in/models/account.py", line 75, in action_post
    return super().action_post()
  File "/home/odoo/src/user/OCA/l10n-italy/l10n_it_withholding_tax/models/account.py", line 399, in action_post
    res = super().action_post()
  File "/home/odoo/src/odoo/addons/sale/models/account_move.py", line 14, in action_post
    res = super(AccountMove, self).action_post()
  File "/home/odoo/src/odoo/addons/account/models/account_move.py", line 2786, in action_post
    self._post(soft=False)
  File "/home/odoo/src/user/OCA/account-fiscal-rule/account_avatax_oca/models/account_move.py", line 342, in _post
    invoice.avatax_compute_taxes(commit=False)
  File "/home/odoo/src/user/OCA/account-fiscal-rule/account_avatax_oca/models/account_move.py", line 310, in avatax_compute_taxes
    invoice._avatax_compute_tax(commit=commit)
  File "/home/odoo/src/user/OCA/account-fiscal-rule/account_avatax_oca/models/account_move.py", line 274, in _avatax_compute_tax
    if avatax_config.override_line_taxes
Exception
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'avalara.salestax' object has no attribute 'override_line_taxes'
